# NumPy: Numerical Python

NumPy is a library for numerical computations in Python. It provides:
- Fast and memory-efficient array operations
- Tools for mathematical, logical, and statistical computations
- Broadcasting and vectorized operations

In [3]:
pip install numpy


  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/bc/49/d5781eaa1a15acb3b3a3f49dc9e2ff18d92d0ce5c2976f4ab5c0a7360250/numpy-2.3.0-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.9 kB 682.7 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/60.9 kB 445.2 kB/s eta 0:00:01
     -------------------------------------- 60.9/60.9 kB 405.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.7 MB 1.7 MB/s eta 0:00:08
   ---------------------------------------- 0.1/12.7 MB 1.1 MB/s eta 0:00:13
    --------------------------------------- 0.2/12.7 MB 1.5 MB/s eta 0:00:09
    --------------------------------------- 0.3/12.7 MB 1.6 MB/s eta 0:00:08
   - -------------------------------------- 0.5/12.7 MB 2.0 MB/s eta 0:00:07
   - ------------------------


[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np 

In [9]:
import time 
a=list(range(100000))
b=list(range(100000))

start = time.time()
result=[x+y for x,y in zip(a,b)]
end=time.time()
print("python list time: ",end-start)

python list time:  0.008319377899169922


In [11]:
a_np=np.arange(100000)
b_np=np.arange(100000)

start=time.time()
result_np= a_np+b_np
end=time.time()
print("Numpy Array time: ",end-start)

Numpy Array time:  0.001013040542602539


In [13]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [16]:
a=np.array([1,2,3])
b=2
c=a*b
print(c)

[2 4 6]


In [20]:
#from python list
a=np.array([1,2,3,4,5])
print("1D Array :",a)
a.ndim

1D Array : [1 2 3 4 5]


1

In [24]:
b=np.array([[1,2,3],[4,5,6]])
print("2D Array: \n",b)
b.ndim

2D Array: 
 [[1 2 3]
 [4 5 6]]


2

In [29]:
c = np.array([[[1,2,3],[2,3,4],[3,4,5]], [[4,5,6],[5,6,7],[6,7,8]]])
print("3D Array: \n",c)
c.ndim

3D Array: 
 [[[1 2 3]
  [2 3 4]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]
  [6 7 8]]]


3

In [31]:
#using builtin function
zeros=np.zeros((2,3),dtype=int)
ones=np.ones((3,2))
arange=np.arange(0,10,2)
linspace=np.linspace(0,1,5)

print("Zeros: \n",zeros,"\nOnes: \n",ones,"\nArange: \n",arange,"\nLinspace: \n",linspace)

Zeros: 
 [[0 0 0]
 [0 0 0]] 
Ones: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]] 
Arange: 
 [0 2 4 6 8] 
Linspace: 
 [0.   0.25 0.5  0.75 1.  ]


In [32]:
#indexing 
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Element at row 1, col 2: ",arr[0,1])

Element at row 1, col 2:  20


In [33]:
#slicing
print("\nFirst two rows: \n",arr[:2])
print("\nLAst column: \n",arr[:,-1])

print("\nElements > 50:\n",arr[arr>50])


First two rows: 
 [[10 20 30]
 [40 50 60]]

LAst column: 
 [30 60 90]

Elements > 50:
 [60 70 80 90]


In [35]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print("Addition: ",x+y)
print("Substraction: ",x-y)
print("Multiplication:",x+y)
print("Scalar Multiplication:",x*10)

Addition:  [5 7 9]
Substraction:  [-3 -3 -3]
Multiplication: [5 7 9]
Scalar Multiplication: [10 20 30]


In [41]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,0],[1,2]])
print("\nMatrix Multiplication: \n",a @ b)

print("Mean of x: ",np.mean(x))
print("Standard deviation of x:",np.std(x))
print("Max of y: ",np.max(y))
print("Min of y: ",np.min(y))


Matrix Multiplication: 
 [[ 4  4]
 [10  8]]
Mean of x:  2.0
Standard deviation of x: 0.816496580927726
Max of y:  6
Min of y:  4


In [44]:
mat1 = np.array([[1, 2],
              [3, 4]])
mat2 = np.array([[2, 0],
              [1, 2]])

# [1, 2]*[2,1]  [1, 2]*[0,2]
# [3, 4]*[2,1]  [3, 4]*[0,2]

result=np.dot(mat1,mat2)
print("Matrix Multiplication: \n",result)

Matrix Multiplication: 
 [[ 4  4]
 [10  8]]


In [47]:
arr=np.arange(20)
print(arr)

shaped=arr.shape
print("Shape array: \n",shaped)

reshaped=arr.reshape(2,10)
print("Reshaped: \n",reshaped)

flattened=arr.flatten()
print("Flattened: ",flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Shape array: 
 (20,)
Reshaped: 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
Flattened:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [59]:
#Broadcasting 
a=np.array([[1],[2],[3]])
b=np.array(([10,20,30]))
c=a+b
print("\nBroadcasted Addition:\n",c)
print("Last elements of each rows:")
print(c[:,-1])
print(c[1:2,-2])
print(c[1][1])



Broadcasted Addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]
Last elements of each rows:
[31 32 33]
[22]
22


## Array Data Types (dtype)

arr_int = np.array([1, 2, 3])
print("Data type:", arr_int.dtype)
print("Data type:", type(arr_int))

arr_float = np.array([1.5, 2.6, 3.9])
print("Float dtype:", arr_float.dtype)

# Convert to int
converted = arr_float.astype(int)
print("Converted to int:", converted)

In [61]:
#copy vs view
x=np.array([1,2,3,4,5])
copy_x=x.copy()
view_x=x.view()
print("Original: ",x)
print("View: ",view_x)
print("Copy: ",copy_x)
x[0]=99

print("After change: ",x)
print("Copy: ",copy_x)
print("View: ",view_x)


Original:  [1 2 3 4 5]
View:  [1 2 3 4 5]
Copy:  [1 2 3 4 5]
After change:  [99  2  3  4  5]
Copy:  [1 2 3 4 5]
View:  [99  2  3  4  5]


`view_x = x.view()`

 * Makes a shallow copy (a view):

 * A new array object is created.

 * But it shares the same data buffer as x.

* So any change to the data in x is reflected in view_x.

In [62]:
print(copy_x is x)
print(view_x is x)  

# Check if they share the same data buffer
print(np.shares_memory(x, copy_x))   # False
print(np.shares_memory(x, view_x))

False
False
False
True


In [83]:
array1=np.arange(1,17)
array1=array1.reshape(4,4)
print(array1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [84]:
array1[1:3,1:3]


array([[ 6,  7],
       [10, 11]])

In [86]:
array2=np.arange(17,1,-1)
array2=array2.reshape(4,4)
print(array2)


[[17 16 15 14]
 [13 12 11 10]
 [ 9  8  7  6]
 [ 5  4  3  2]]


In [91]:
mul=array1.dot(array2)
print(mul)

[[ 90  80  70  60]
 [266 240 214 188]
 [442 400 358 316]
 [618 560 502 444]]


In [94]:
array2=array2.astype(float)
array2=array2.reshape(2,8)
print(array2)

[[17. 16. 15. 14. 13. 12. 11. 10.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.]]


In [101]:
a1=np.array([[1],[2],[3]])
a2=np.arange(4,1,-1)
asum=a1+a2
print(asum)

[[5 4 3]
 [6 5 4]
 [7 6 5]]


In [117]:
a1=np.array([1,2,3])
a2=np.arange(1,4)
asum=a1*a2
print(asum)

[1 4 9]
